#!/bin/bash

# Why installing ROS is a PITA
# - They don't believe in 'sudo apt-add-repository ppa:ros/kinetic'
# - They want you to memorize some key instead

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
sudo apt-get update
sudo apt-get install -y ros-kinetic-desktop-full python-pip python3-pip
sudo pip install rospkg catkin_pkg
sudo pip3 install rospkg catkin_pkg

